version: '3'

services:
  
  postgres:
    image: postgres
    container_name: "postgres"
    #hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - ./postgres-data/var/lib/postgresql/data
    restart: unless-stopped
#    networks:
#      - postgres-compose-network



#  postgres:
#    image: "postgres" # use latest official postgres version
#    env_file:
#      - database.env # configure postgres
#    volumes:
#      - ./database-data/var/lib/postgresql/data # persist data even if container shuts down
#  volumes:
#    database-data: # named volumes can be managed easier using docker-compose

#####################################################3


  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin4"
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: student@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: student
    #environment: "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - ./postgres-data/var/lib/pgadmin4/data
    restart: unless-stopped
#    networks:
#      - postgres-compose-network

volumes:
  postgres-data:

#networks: 
#  postgres-compose-network:
#    driver: bridge