version: '3'

services:
  
  postgres:
    image: postgres
    container_name: "postgres"
    #hostname: postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - ./postgres-data/var/lib/postgresql/data
    restart: unless-stopped

###

  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin4"
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: student@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: student
    #environment: "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - ./postgres-data/var/lib/pgadmin4/data
    restart: unless-stopped

volumes:
  postgres-data:
